server:
  port: 8001

spring:
  application:
    name: eureka-provider
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} # 设置web控制台显示的 实例id
    # 每一次eureka client 向 eureka server发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 30
    # 如果90秒内eureka server没有收到eureka client的心跳包，则剔除该服务
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # 是否注册自己，eureka server不需要的  client需要
    register-with-eureka: true
    # 是否需要从eureka中抓取路径。eureka server不需要的  client需要
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

title: s-s-jiaozx
